 version: '3.8'
 services:
   app:
     build: .
     container_name: git-branch-switcher
     ports:
       - "8080:8080"
     volumes:
       - ${HOST_REPO_PATH}:/app/repo
       - ~/.ssh:/root/.ssh:ro